language: python

python:
    - "2.7"
    - "3.6"

install:
    - pip install flake8
    - pip install setuptools

script:
    - make check
    - make test

notifications:
  email:
    on_success: never
    on_failure: always

